#!/usr/bin/env python3
"""Phase 2.1-2.3 — clean, dedup, relabel (use-mention) + regenerate explanations.

Pipeline over data/combined_multilingual_20k.csv:
  1. sentence-quality filter: drop rows whose SENTENCE is corrupted (CJK, empty).
     (Explanations are discarded wholesale — they are ~88% augmentation-meta in both
      languages — and regenerated by the judge for kept violations.)
  2. dedup: exact-duplicate sentences within the set (keep first) + drop any sentence
     matching a frozen eval sentence (expert_eval / gold_eval), normalized. NO LEAKAGE.
  3. Correct rows -> target empty issues (no judge call).
     Violation rows -> Gemma judge: keep/flip + category + clean explanation (Phase 2.2,
     gate passed at 0.879 agreement). flip_to_correct rows become Correct (empty issues).

Outputs:
  ml/data_curated/curated.jsonl     intermediate rows (one per training example)
  ml/data_curated/relabel_audit.csv every judge decision (human spot-check)
  ml/data_curated/relabel_stats.json
"""
import csv
import json
import os
import re
import sys
from concurrent.futures import ThreadPoolExecutor

from gemma_judge import judge

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(REPO, "data", "combined_multilingual_20k.csv")
EXPERT = os.path.join(REPO, "ml", "eval_sets", "expert_eval.jsonl")
GOLD = os.path.join(REPO, "ml", "eval_sets", "gold_eval.jsonl")
OUT_JSONL = os.path.join(HERE, "curated.jsonl")
AUDIT = os.path.join(HERE, "relabel_audit.csv")
STATS = os.path.join(HERE, "relabel_stats.json")
CONCURRENCY = 20

CJK = re.compile(r"[一-鿿぀-ヿ가-힣]")


def norm(s):
    s = s.lower().strip()
    s = re.sub(r"[^\w\s]", "", s, flags=re.UNICODE)
    return re.sub(r"\s+", " ", s)


def load_eval_sentences():
    ev = set()
    for path in (EXPERT, GOLD):
        for line in open(path, encoding="utf-8"):
            ev.add(norm(json.loads(line)["sentence"]))
    return ev


def main():
    rows = list(csv.DictReader(open(SRC, encoding="utf-8")))
    eval_norms = load_eval_sentences()
    stats = {"raw": len(rows)}

    # 1. sentence-quality filter
    kept = []
    dropped_quality = 0
    for r in rows:
        s = (r["sentence"] or "").strip()
        if len(s) < 5 or CJK.search(s):
            dropped_quality += 1
            continue
        kept.append(r)
    stats["dropped_quality"] = dropped_quality

    # 2. dedup (within-set exact + against eval)
    seen, deduped, leak = set(), [], 0
    for r in kept:
        n = norm(r["sentence"])
        if n in eval_norms:
            leak += 1
            continue
        if n in seen:
            continue
        seen.add(n)
        deduped.append(r)
    stats["dropped_eval_leak"] = leak
    stats["dropped_dup"] = len(kept) - leak - len(deduped)
    stats["after_clean_dedup"] = len(deduped)
    print(f"raw={stats['raw']} quality_drop={dropped_quality} eval_leak={leak} "
          f"dup={stats['dropped_dup']} -> {len(deduped)}", flush=True)

    violations = [r for r in deduped if r["severity_label"] != "Correct"]
    corrects = [r for r in deduped if r["severity_label"] == "Correct"]
    print(f"correct={len(corrects)} violations(to judge)={len(violations)}", flush=True)

    # 3. judge violations (concurrent, cached)
    done = [0]

    def run(r):
        res = judge(r["sentence"], r["severity_label"], r["language"])
        done[0] += 1
        if done[0] % 500 == 0:
            print(f"  judged {done[0]}/{len(violations)}", flush=True)
        return r, res

    judged = []
    with ThreadPoolExecutor(max_workers=CONCURRENCY) as ex:
        for r, res in ex.map(run, violations):
            judged.append((r, res))

    # assemble curated rows + audit
    out, audit_rows = [], []
    n_flip = n_keep = n_err = n_lang_warn = 0
    cat_counter = {}
    for r in corrects:
        out.append({"sentence": r["sentence"], "language": r["language"],
                    "label": "Correct", "category": None, "phrase": None,
                    "explanation": None, "source_label": "Correct", "origin": "correct"})
    for r, res in judged:
        src = r["severity_label"]
        if "_error" in res:
            n_err += 1
            # conservative fallback: keep as violation, no regenerated explanation
            out.append({"sentence": r["sentence"], "language": r["language"],
                        "label": src, "category": "Generalization", "phrase": r["sentence"],
                        "explanation": None, "source_label": src, "origin": "judge_error"})
            audit_rows.append([r["language"], src, "ERROR", "", res.get("_error", ""), r["sentence"]])
            continue
        if res["verdict"] == "flip_to_correct":
            n_flip += 1
            out.append({"sentence": r["sentence"], "language": r["language"],
                        "label": "Correct", "category": None, "phrase": None,
                        "explanation": None, "source_label": src, "origin": "flip"})
            audit_rows.append([r["language"], src, "Correct", "", res.get("_reason", ""), r["sentence"]])
        else:
            n_keep += 1
            cat = res.get("category") or "Generalization"
            cat_counter[cat] = cat_counter.get(cat, 0) + 1
            if res.get("_lang_warn"):
                n_lang_warn += 1
            out.append({"sentence": r["sentence"], "language": r["language"],
                        "label": src, "category": cat,
                        "phrase": res.get("phrase") or r["sentence"],
                        "explanation": res.get("explanation"),
                        "source_label": src, "origin": "keep"})
            audit_rows.append([r["language"], src, src, cat,
                               (res.get("explanation") or "")[:120], r["sentence"]])

    with open(OUT_JSONL, "w", encoding="utf-8") as f:
        for o in out:
            f.write(json.dumps(o, ensure_ascii=False) + "\n")
    with open(AUDIT, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["language", "source_label", "new_label", "category", "judge_reason_or_expl", "sentence"])
        w.writerows(audit_rows)

    from collections import Counter
    stats.update({
        "judged": len(judged), "flip_to_correct": n_flip, "kept_violation": n_keep,
        "judge_errors": n_err, "lang_warnings": n_lang_warn, "categories": cat_counter,
        "final_rows": len(out),
        "final_label_dist": dict(Counter(o["label"] for o in out)),
        "final_lang_dist": dict(Counter(o["language"] for o in out)),
        "final_correct_share": round(sum(1 for o in out if o["label"] == "Correct") / len(out), 3),
    })
    json.dump(stats, open(STATS, "w"), ensure_ascii=False, indent=2)
    print("\n=== RELABEL STATS ===")
    print(json.dumps(stats, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
